---
services: docker

env:
  global:
    php_version: "7.1"

  matrix:
    # Default - PHP 7.1
    - distro: centos7
    - distro: debian9
    - distro: ubuntu1804
    - distro: ubuntu1604

    # PHP 7.2
    - distro: centos7
      playbook: test-7.2.yml
      php_version: "7.2"
    - distro: ubuntu1804
      playbook: test-7.2.yml
      php_version: "7.2"
    - distro: ubuntu1604
      playbook: test-7.2.yml
      php_version: "7.2"
    - distro: debian9
      playbook: test-7.2.yml
      php_version: "7.2"

    # PHP 5.6
    - distro: centos7
      playbook: test-5.6.yml
      php_version: "5.6"
    - distro: ubuntu1804
      playbook: test-5.6.yml
      php_version: "5.6"

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Run script to test PHP version.
  - 'docker exec ${container_id} env TERM=xterm php -v | grep -F "${php_version}."'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
