# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Redis | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'redis'
    - 'redis-package'
    - 'redis-configure'
    - 'redis-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Redis | Define Redis packages.'
  set_fact:
    redis_packages: '{{ redis_default_packages }}'
  when: 'not redis_packages'
  tags:
    - 'redis'
    - 'redis-package'
    - 'redis-configure'
    - 'redis-service'
    - 'package'
    - 'configure'
    - 'service'

- include: 'package.yml'
  tags:
    - 'redis'
    - 'redis-package'
    - 'package'

- include: 'configure.yml'
  tags:
    - 'redis'
    - 'redis-configure'
    - 'configure'

- include: 'service.yml'
  tags:
    - 'redis'
    - 'redis-service'
    - 'service'