# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Composer | Define PHP executable.'
  set_fact:
    php_executable: 'php'
  when: 'php_executable is not defined'
  tags:
    - 'composer'
    - 'composer-package'
    - 'composer-configure'
    - 'package'
    - 'configure'

- include: 'package.yml'
  tags:
    - 'composer'
    - 'composer-package'
    - 'package'

- include: 'configure.yml'
  tags:
    - 'composer'
    - 'composer-configure'
    - 'configure'