# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Composer | Determine whether Composer is installed.'
  become: yes
  stat:
    path: '{{ composer_path }}'
  register: 'composer_bin'

- name: 'Composer | Download the installation file.'
  become: yes
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer-installer.php'
    mode: '0755'
  when: 'not composer_bin.stat.exists'

- name: 'Composer | Run the installation file.'
  become: yes
  command: '{{ php_executable }} composer-installer.php {% if composer_version %} --version={{ composer_version }}{% endif %}'
  args:
    chdir: '/tmp'
  when: 'not composer_bin.stat.exists'

- name: 'Composer | Ensure Composer is globally accessible.'
  become: yes
  command: 'mv /tmp/composer.phar {{ composer_path }}'
  args:
    creates: '{{ composer_path }}'
    removes: '/tmp/composer.phar'
  when: 'not composer_bin.stat.exists'

- name: 'Composer | Update Composer to latest version.'
  become: yes
  command: '{{ php_executable }} {{ composer_path }} self-update'
  register: 'composer_update'
  changed_when: '"Updating to version" in composer_update.stdout'
  when: 'composer_keep_updated'