---
- hosts: all
  become: yes

  vars:
    php_version: '7.2'
    php_packages_extra:
      - php7.2-bcmath
      - php7.2-bz2
      - php7.2-dba
      - php7.2-gmp
      - php7.2-imap
      - php7.2-intl
      - php7.2-ldap
      - php7.2-interbase
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-obdc
      - php7.2-pgsql
      - php7.2-pspell
      - php7.2-readline
      - php7.2-snmp
      - php7.2-skybase
      - php7.2-tidy
      - php7.2-xmlrpc

  pre_tasks:
    - include: tasks/general-packages.yml

    #- include: tasks/php-7-2.yml

  roles:
    - { role: geerlingguy.php-versions }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.git }
    - { role: geerlingguy.nodejs }
    - { role: geerlingguy.redis }
    - { role: ocha.yarn }
    - { role: phansible.sqlite }
