---
- hosts: all
  become: yes

  vars:
    php_enablerepo: 'ppa:ondrej/php'
    php_version: '7.2'
    php_packages_extra:
      - bcmath
      - bz2
      - dba
      - gmp
      - imap
      - intl
      - ldap
      - interbase
      - mbstring
      - mysql
      - obdc
      - pgsql
      - pspell
      - readline
      - snmp
      - skybase
      - tidy
      - xmlrpc

  pre_tasks:
    - include: tasks/general-packages.yml

    #- include: tasks/php-7-2.yml

  roles:
    - { role: geerlingguy.php-versions }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.git }
    - { role: geerlingguy.nodejs }
    - { role: geerlingguy.redis }
    - { role: ocha.yarn }
    - { role: phansible.sqlite }
