---
- hosts: all
  become: yes

  pre_tasks:
    - include: tasks/general-packages.yml

    - include: tasks/php-7-2.yml

  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.nodejs }
    - { role: ontic.composer }
    - { role: ontic.redis }
    - { role: ocha.yarn }
    - { role: webofmars.phpunit }
    - { role: phansible.sqlite }
