---
- hosts: all
  become: yes

  vars:
    extra_path: /vendor/bin
    php_version: '7.2'
    php_packages_extra:
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-bz2"
      - "php{{ php_version }}-dba"
      - "php{{ php_version }}-gmp"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-ldap"
      - "php{{ php_version }}-interbase"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-odbc"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-pspell"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-snmp"
      - "php{{ php_version }}-sybase"
      - "php{{ php_version }}-tidy"
      - "php{{ php_version }}-xmlrpc"

  pre_tasks:
    - include: tasks/general-packages.yml
    - include: tasks/add-extra-path.yml

  roles:
    - { role: geerlingguy.php-versions, when: php_version != '', tags: ['php'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['php'] }
    - { role: geerlingguy.git }
    - { role: geerlingguy.nodejs }
    - { role: geerlingguy.redis }
    - { role: ocha.yarn }
    - { role: phansible.sqlite }
