- src: phansible.sqlite
- src: ocha.yarn
- src: geerlingguy.redis
- src: geerlingguy.git
- src: geerlingguy.mysql
- src: geerlingguy.nodejs
- src: geerlingguy.php
- src: geerlingguy.php-versions
- src: geerlingguy.composer
- src: geerlingguy.php-redis
