---
roles:
  - src: phansible.sqlite
  - src: geerlingguy.git
  - src: geerlingguy.nodejs
  - src: geerlingguy.php
  - src: geerlingguy.php-versions
  - src: geerlingguy.composer
  - src: geerlingguy.php-redis
  - src: dgibbs64.nodejs

collections:
  - community.general
  - community.crypto
  - ansible.netcommon
  - ansible.utils
