---
galaxy_info:
  author: Natalio Ruiz
  description: NodeJS
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
  - development

dependencies: []